#!/bin/bash

readonly VERSION="1.38.0"

main() {
  curl -LO "https://github.com/dhall-lang/dhall-haskell/releases/download/${VERSION}/dhall-${VERSION}-x86_64-linux.tar.bz2"

  tar xf "dhall-${VERSION}-x86_64-linux.tar.bz2" ./bin/dhall

  mkdir -p ~/.local/bin

  cp ./bin/dhall ~/.local/bin
}

main "${@}"
