#!/bin/bash

readonly VERSION="1.38.0"

# CI install

main() {
  mkdir -p ~/.local/bin

  for package_name in dhall dhall-json; do
    curl -LO "https://github.com/dhall-lang/dhall-haskell/releases/download/${VERSION}/${package_name}-${VERSION}-x86_64-linux.tar.bz2"
    tar xf "${package_name}-${VERSION}-x86_64-linux.tar.bz2" ./bin
    cp ./bin/* ~/.local/bin
    rm -rf ./bin
  done
}

main "${@}"
